import type { Recommendation } from '@/types/domain';

// Static, pre-authored recommendations for the M1 walkthrough. From M3 onward these are
// generated by the evaluation/recommendation engine (SDS §14, §15, §17) instead of hand-written.
export const mockRecommendations: Recommendation[] = [
  {
    id: 'rec_add_heat_protectant',
    decision: 'add_step',
    summary: 'Add a heat protectant',
    whyThisHelps:
      'You use heat often but don’t have a heat protectant in your routine, which raises the risk of heat damage.',
    relatedProductIds: ['prod_keracare_thermal_wonder'],
  },
  {
    id: 'rec_leave_in_more_moisture',
    decision: 'offer_alternative',
    summary: 'Try a leave-in with more moisture',
    whyThisHelps: 'Your porosity is high, so a richer leave-in can help hair hold moisture longer.',
    relatedProductIds: ['prod_sheamoisture_jbco_leave_in'],
  },
  {
    id: 'rec_protein_overdue',
    decision: 'add_step',
    summary: 'Protein treatment may be overdue',
    whyThisHelps:
      'Your routine has no protein step recorded in the last few wash cycles, which can lead to over-conditioned, mushy strands.',
    relatedProductIds: [],
  },
  {
    id: 'rec_clarify_more_often',
    decision: 'adjust_usage',
    summary: 'Consider clarifying more often',
    whyThisHelps:
      'Frequent stylers without a regular clarifying step can lead to product buildup over time.',
    relatedProductIds: ['prod_mielle_rosemary_shampoo'],
  },
];
